import tkinter as tk
from tkinter import scrolledtext, filedialog, messagebox
import speech_recognition as sr
import threading
import os
from dotenv import load_dotenv
from llm_integration import GeminiCodeAssistant  

def format_markdown_for_tk(text):
        lines = text.split("\n")
        formatted = []

        for line in lines:
            # Format headings
            if line.startswith("###"):
                formatted.append("\n" + line.replace("###", "").strip().upper())
                formatted.append("-" * 40)
                continue

            # Format bold text
            if "**" in line:
                line = line.replace("**", "")

            # Format code blocks
            if line.startswith("```"):
                formatted.append("\n------------------ CODE ------------------")
                continue

            # Bulleted list
            if line.strip().startswith("*"):
                formatted.append(" • " + line.replace("*", "").strip())
                continue

            formatted.append(line)

        return "\n".join(formatted)


class VoiceCodeIDE:
    def __init__(self, root):
        self.root = root
        self.root.title("Voice-Powered Code Editor")
        self.root.geometry("900x700")

        load_dotenv()
        gemini_api_key = os.getenv("API_KEY")
        if not gemini_api_key:
            messagebox.showerror("Config Error", "Gemini API key not found in .env file. Please set it as API_KEY=your_key.")
            self.root.destroy()
            return

        self.gemini_assistant = GeminiCodeAssistant(api_key=gemini_api_key)

        self.text_editor = scrolledtext.ScrolledText(root, wrap=tk.WORD, font=("Consolas", 12))
        self.text_editor.pack(expand=True, fill='both', padx=10, pady=10)

        self.status_bar = tk.Label(root, text="Status: Ready", bd=1, relief=tk.SUNKEN, anchor=tk.W)
        self.status_bar.pack(side=tk.BOTTOM, fill=tk.X)

        self.listen_button = tk.Button(root, text="Start Listening", command=self.start_listening_thread)
        self.listen_button.pack(side=tk.BOTTOM, pady=10)

        self.debug_button = tk.Button(root, text="Open Debug Window", command=self.open_debug_window)
        self.debug_button.pack(side=tk.BOTTOM, pady=10)


        self.recognizer = sr.Recognizer()
        self.microphone = sr.Microphone()

    def update_status(self, message):
        self.status_bar.config(text=f"Status: {message}")

    def start_listening_thread(self):
        self.listen_button.config(state=tk.DISABLED, text="Listening...")
        self.update_status("Listening for a command...")
        thread = threading.Thread(target=self.listen_for_command)
        thread.daemon = True
        thread.start()

    def listen_for_command(self):
        try:
            with self.microphone as source:
                self.recognizer.adjust_for_ambient_noise(source)
                audio = self.recognizer.listen(source)
            
            command = self.recognizer.recognize_google(audio).lower()
            self.update_status(f"Recognized: '{command}'")
            
            self.root.after(0, self.execute_command, command)

        except sr.UnknownValueError:
            self.update_status("Could not understand audio. Please try again.")
        except sr.RequestError as e:
            self.update_status(f"API error: {e}")
        finally:
            self.root.after(0, lambda: self.listen_button.config(state=tk.NORMAL, text="Start Listening"))

    def execute_command(self, command):
        """
        Interprets the command and acts accordingly.
        This is the new, simplified logic!
        """
        if "open code" in command:
            self.open_file()
        elif "save file" in command:
            self.save_file()
        else:
            self.update_status(f"🤖 Sending to Gemini: '{command}'...")
            self.root.update_idletasks()

            generated_code = self.gemini_assistant.generate_code(command)
            
            if generated_code.strip().startswith("# ERROR"):
                self.update_status(f"⚠️ {generated_code}")
            else:
                self.text_editor.insert(tk.INSERT, generated_code + "\n\n")
                self.update_status("✅ Code generated by Gemini.")

    def save_file(self):
        file_path = filedialog.asksaveasfilename(defaultextension=".py",
                                                 filetypes=[("Python files", "*.py"), ("All files", "*.*")])
        if file_path:
            with open(file_path, 'w') as file:
                file.write(self.text_editor.get(1.0, tk.END))
            self.update_status(f"File saved to {file_path}")

    def open_file(self):
        file_path = filedialog.askopenfilename(filetypes=[("Python files", "*.py"), ("All files", "*.*")])
        if file_path:
            with open(file_path, 'r') as file:
                self.text_editor.delete(1.0, tk.END)
                self.text_editor.insert(tk.INSERT, file.read())
            self.update_status(f"File opened from {file_path}")


    def open_debug_window(self):
        debug_window = tk.Toplevel(self.root)
        debug_window.title("Debug Code")
        debug_window.geometry("900x700")

        # Input label
        tk.Label(debug_window, text="Paste Your Code Below:", font=("Calibri", 12, "bold")).pack(pady=5)

        # Text editor for code input
        input_box = scrolledtext.ScrolledText(debug_window, wrap=tk.WORD, height=15, font=("Consolas", 12))
        input_box.pack(fill="both", padx=10, pady=10, expand=True)

        # Output label
        tk.Label(debug_window, text="Debug Output:", font=("Calibri", 12, "bold")).pack(pady=5)

        # Output display
        output_box = scrolledtext.ScrolledText(debug_window, wrap=tk.WORD, height=15, font=("Consolas", 12))
        output_box.pack(fill="both", padx=10, pady=10, expand=True)

        # Button to debug
        def run_debug():
            code = input_box.get("1.0", tk.END)
            if not code.strip():
                messagebox.showwarning("Empty", "Please paste some code first.")
                return

            output_box.delete("1.0", tk.END)
            output_box.insert(tk.END, "Debugging... Please wait.\n")

            try:
                result = self.gemini_assistant.debug_code(code)
                formatted = format_markdown_for_tk(result)
                output_box.delete("1.0", tk.END)
                output_box.insert(tk.END, formatted)
            except Exception as e:
                output_box.insert(tk.END, f"\nError: {str(e)}")

        tk.Button(debug_window, text="DEBUG CODE", command=run_debug, bg="blue", fg="white", padx=10, pady=5).pack(pady=10)


if __name__ == "__main__":
    root = tk.Tk()
    app = VoiceCodeIDE(root)
    root.mainloop()

